# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'RangelEnterprisesBM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JTAppleCalendar', '~> 7.0'

  # Pods for RangelEnterprisesBM

  target 'RangelEnterprisesBMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RangelEnterprisesBMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
